# Generated by Django 4.1.1 on 2022-09-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0002_apidata_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apidata',
            name='img',
        ),
    ]
