# Generated by Django 4.1.1 on 2022-09-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0003_remove_apidata_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidata',
            name='img',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
