# Generated by Django 4.1.1 on 2022-10-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0004_apidata_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
    ]
